server:
  tomcat:
    max-swallow-size: -1  # request size 제한 해제
    max-http-form-post-size: 100MB  # HTTP POST MAX size

spring:
  profiles:
    active:
      - dev
    include:
      - secret
      - dev

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: false
        #        format_sql: true
        default_batch_fetch_size: 1000

  servlet:
    multipart:
      enabled: true
      maxFileSize: 100MB
      maxRequestSize: 100MB

  datasource:
    - secret
    - dev

  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: true

  messages:
    encoding: UTF-8

springdoc:
  version: 0.0.1
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    path: /swagger-ui.html

logging:
  level:
    org.hibernate.SQL: debug